### ISSUE TITLE
Cannot connect to host when running in dataproc

### ISSUE THREAD

**Issue by pepperbc** [fsspec/gcsfs#444]
When running in dataproc, I get the following error: 

`aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host storage.googleapis.com:443 ssl:default [Network is unreachable]
`
I have tried using both None, "cloud", and "google_default" for token. (I believe "cloud" is the correct option but not 100% sure). I am able to successfully read from the same bucket using the standard google.cloud.storage.Client, so authentication works there at least. I'm unsure what gcsfs is doing differently that would be causing this. I'm guessing I can fix this with some sort of dataproc config (firewall?), but since the standard gs client works, I'm wonderings why gcsfs doesn't.

Any help would be appreciated. Thanks!

Stack trace below: 
```
Traceback (most recent call last):
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/lib/python3.7/asyncio/base_events.py", line 949, in create_connection
    await self.sock_connect(sock, address)
  File "/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/lib/python3.7/asyncio/selector_events.py", line 478, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.7/site-packages/gcsfs/retry.py", line 115, in retry_request
    return await func(*args, **kwargs)
  File "/lib/python3.7/site-packages/gcsfs/core.py", line 370, in _request
    timeout=self.requests_timeout,
  File "/lib/python3.7/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/lib/python3.7/site-packages/aiohttp/client.py", line 536, in _request
    req, traces=traces, timeout=real_timeout
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 1187, in _create_direct_connection
    client_error=client_error,
  File "/lib/python3.7/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc

```

This eventually causes a ```OSError: Passed non-file path: gs://``` for the file I was trying to retrieve

**Comment by martindurant** [comment]
I'm afraid I don't know what dataproc is. The error seems to say that your machine cannot see the storage server at all, so this is a step before any authentication. Might it be an intermittent network issue?

The following OS error: I'm not sure where this is coming from, but presumably solving the first issue would fix it.

**Comment by pepperbc** [comment]
Dataproc is a gcs service for Spark, etc. jobs. Doesn't seem to be intermittent - happens every time. For whatever reason it doesn't happen to the normal gs client - do you connect to the storage servers differently? 

And are you sure it happens before authentication? I was initially specifying a project and it was telling me the project didn't match, which seemed to be part of the authentication step.

**Comment by martindurant** [comment]
> do you connect to the storage servers differently

We call HTTP requests on a particular API server. I have no idea is the gs client does something else.

@efiop , perhaps you know of people using GCS inside dataproc.

> Can you provide more details about the when authentication happens

You can turn on the "gcsfs" and "gcsfs.credentials" loggers at debug level to get more messaging from gcsfs itself, if you like. However, authentication happens during initial contact with storage.googleapis.com, which is apparently unreachable. You need to talk to that endpoint to do anything with gcsfs. The project may be derived from metadata service or local token files, so that error does not mean that auth had already happened.
