### ISSUE TITLE
Unable to use ls and open operations because of threading error

### ISSUE THREAD

**Issue by SwarnaBharathiMantena** [fsspec/gcsfs#465]
Hi, I tried the ls() and open() operations following the examples stated here: https://gcsfs.readthedocs.io/en/latest/ 
I get no result for both the calls. When I interrupt, I see the traceback as mentioned below.

```
import gcsfs
import pandas as pd

fs = gcsfs.GCSFileSystem(project='<my-bucket-name>', access="read_only")
with fs.open('<my-bucket-name>/<my-blob-name>.pickle', 'rb') as f:
    df = pd.read_csv(f) 
print(df)
```

Traceback:

^CTraceback (most recent call last):
  File "./test/test_bucket_creation.py", line 122, in <module>
    with fs.open('my-workbench-bucket-90e20451-938e-4665-856c-a90a45083a40/sxmant4_test_1.pickle', 'rb') as f:
  File "/opt/anaconda3/lib/python3.8/site-packages/fsspec/spec.py", line 1009, in open
    f = self._open(
  File "/opt/anaconda3/lib/python3.8/site-packages/gcsfs/core.py", line 1150, in _open
    return GCSFile(
  File "/opt/anaconda3/lib/python3.8/site-packages/gcsfs/core.py", line 1270, in __init__
    super().__init__(
  File "/opt/anaconda3/lib/python3.8/site-packages/fsspec/spec.py", line 1351, in __init__
    self.size = self.details["size"]
  File "/opt/anaconda3/lib/python3.8/site-packages/fsspec/spec.py", line 1364, in details
    self._details = self.fs.info(self.path)
  File "/opt/anaconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 85, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in sync
    if event.wait(1):
  File "/opt/anaconda3/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/anaconda3/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

Would like to know if I am doing something wrong here, or if there is an issue to be fixed.
Thank you!

**Comment by martindurant** [comment]
Can you please let us know the versions you are using? How is your auth defined?
If you can point to a public URL, all the better, so that we can test too.

**Comment by SwarnaBharathiMantena** [comment]
gcsfs version 2022.2.0
I have not defined auth using 'token' parameter. However, I have default gcloud credentials stored in .bash_profile

Unfortunately it is an internal application which I will not be able to share a URL of.

Could be useful:
When I add a print statement as shown below - 
```
import gcsfs
import pandas as pd

fs = gcsfs.GCSFileSystem(project='<my-bucket-name>', access="read_only")
print("fs =", fs)
with fs.open('<my-bucket-name>/<my-blob-name>.pickle', 'rb') as f:
    df = pd.read_csv(f) 
print(df)
```
It gives an output: fs = <gcsfs.core.GCSFileSystem object at 0x7f8d68304fa0>
So, I think auth is not an issue here

**Comment by SwarnaBharathiMantena** [comment]
Hi, is there any additional information I can provide to get help on this?

**Comment by martindurant** [comment]
I'm afraid I don't have a good idea of what to suggest, I have not heard of this situation before. I can only suppose that something is non-standard about your system :|  Do you use any other asyn or threaded code successfully? Can you list your full set of package versions, please?

**Comment by dingding951001** [comment]
I am also facing the exact same issue. Is there a fix for the issue?

**Comment by dingding951001** [comment]
Below is my dependency:
fsspec==2021.7.0
gcsfs==2021.7.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
google-auth==1.35.0
google-cloud-bigquery-storage==1.1.0
google-cloud-bigquery==1.28.2
google-cloud-core==2.3.1
google-cloud-datastore==2.1.6
google-cloud-logging==3.0.0

**Comment by dingding951001** [comment]
Things broke for me between https://github.com/fsspec/gcsfs/compare/0.6.2...0.7.0
