### ISSUE TITLE
fsspec.open('gs://bucket/not_existing.txt', 'wb') raises FileNotFoundError

### ISSUE THREAD

**Issue by lillekemiker** [fsspec/gcsfs#485]
New behavior when updating from `gcsgf==2022.5.0` and `fsspec==2022.5.0` to `gcsfs==0.8.0` and `fsspec==2022.7.0`.

When opening a new (non-existing) file in write mode
expected behavior: `fsspec.open('gs://bucket/not_existing.txt', 'wb')` returns an `OpenFile` object in write mode
Actual behavior: `fsspec.open('gs://bucket/not_existing.txt', 'wb')` raises a `FileNotFoundError` error

This seems to happen when the `GCSFile` class is instantiated in `gcsfs/core.py` line 1406:
`-> det = getattr(self, "details", {})  # only exists in read mode`
The comment seems to imply that `det` should be assigned the default `{}` when not in read mode. However, the error is raised instead.

full trace:

```
>>> import fsspec
>>> with fsspec.open('gs://sixgill-ml/mkristiansen/temp_debug/test.txt', 'wb') as f:
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/fsspec/core.py", line 104, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/usr/local/lib/python3.8/dist-packages/fsspec/spec.py", line 1034, in open
    f = self._open(
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 1256, in _open
    return GCSFile(
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 1406, in __init__
    det = getattr(self, "details", {})  # only exists in read mode
  File "/usr/local/lib/python3.8/dist-packages/fsspec/spec.py", line 1395, in details
    self._details = self.fs.info(self.path)
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/usr/local/lib/python3.8/dist-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 834, in _info
    out = await self._ls(path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 870, in _ls
    out = await self._list_objects(path, prefix=prefix)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 658, in _list_objects
    return [await self._get_object(path)]
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 612, in _get_object
    res = await self._call("GET", "b/{}/o/{}", bucket, key, json_out=True)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 539, in _call
    self.validate_response(status, contents, path, headers)
  File "/usr/local/lib/python3.8/dist-packages/gcsfs/core.py", line 1311, in validate_response
    raise FileNotFoundError
FileNotFoundError
```

**Comment by martindurant** [comment]
gcsfs 0.8.0 is a significant downgrade of your version. Presumably pip has done something strange while we go through the release cycle of all three packages.

**Comment by lillekemiker** [comment]
Hmm, that's definitely odd. I appreciate the feedback. I'll have to investigate a bit on my end then. Thanks

**Comment by martindurant** [comment]
2022.7.1 is now out on pypi and conda-forge, all should be well

**Comment by lillekemiker** [comment]
This solved the issue. Thanks
