### ISSUE TITLE
gcsfs 2022.8.2 does not work with pyarrow.fs.copy_files (earlier versions work)

### ISSUE THREAD

**Issue by krfricke** [fsspec/gcsfs#498]
When using gcsfs 2022.8.2 with pyarrow.fs.copy_files, we run into the following error:

```
Traceback (most recent call last):
  File "scratch2.py", line 6, in <module>
    pyarrow.fs.copy_files("gs://bucket/subdir", "/tmp/somewhere", source_filesystem=fs)
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pyarrow/fs.py", line 246, in copy_files
    chunk_size, use_threads)
  File "pyarrow/_fs.pyx", line 1229, in pyarrow._fs._copy_files_selector
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'bucket/nested', which is outside base dir 'gs://bucket/nested/subdir'
```

Reproduction script:

```
import pyarrow.fs

from gcsfs import GCSFileSystem

fs = pyarrow.fs.PyFileSystem(pyarrow.fs.FSSpecHandler(GCSFileSystem()))
pyarrow.fs.copy_files(
    "bucket/nested/subdir",
    "/tmp/somewhere",
    source_filesystem=fs)
```

The same code works fine with gcsfs 2022.7.1 and earlier.

Confirmed this does not work with pyarrow 6, 7, 8, and 9.

**Comment by martindurant** [comment]
While I agree that this ought to work and we should fix it, I wonder why you don't do:
```
gcs = GCSFileSystem()
gcs.get("gs://bucket/subdir", "/tmp/somewhere", recursive=True)
```

Also, the error message, which is not too clear, suggests that removing "gs://" from the input URL might fix this.

**Comment by martindurant** [comment]
Probably a moot point, but fsspec.generics is also designed to have a single API entrypoint for working with multiple filesystems by URL. It only currently has cat, not get, though (would be super simple to add).

**Comment by krfricke** [comment]
Ah I've just checked and we're actually not using the `gs://` prefix in our implementation. It works with one subdir, but it fails with nested subdirs:

```
import pyarrow.fs

from gcsfs import GCSFileSystem

fs = pyarrow.fs.PyFileSystem(pyarrow.fs.FSSpecHandler(GCSFileSystem()))
pyarrow.fs.copy_files(
    "bucket/nested/subdir",
    "/tmp/somewhere",
    source_filesystem=fs)
```

I've updated the original issue.

For the fsspec.generics, I believe the pyarrow standardization is too ubiquitous in Ray so we will probably stick with it for now, but thanks for letting me know!

**Comment by martindurant** [comment]
Ah, so specifically, it looks like it is trying to get the info on the directory prior to trying to copy it? I am puzzled that the exception refers to "gs://bucket/nested/subdir", even though that was not in the invocation. I wonder whether this is just a string manipulation thing on their side.
Could you please turn on logger "gcsfs" to see if there is any additional information

```
fsspec.utils.setup_logging(logger_name="gcsfs")
```

**Comment by krfricke** [comment]
Output (replaced actual bucket name with `bucket`):

```
2022-09-26 17:27:43,601 - gcsfs.credentials - DEBUG - connect -- Connected with method google_default
2022-09-26 17:27:43,609 - gcsfs - DEBUG - _call -- GET: b/{}/o/{}, ('bucket', 'nested/subdir'), None
2022-09-26 17:27:43,609 - gcsfs.credentials - DEBUG - maybe_refresh -- GCS refresh
2022-09-26 17:27:43,901 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), None
2022-09-26 17:27:44,269 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), None
Traceback (most recent call last):
  File "scratch2.py", line 12, in <module>
    source_filesystem=fs)
  File "/Users/kai/.pyenv/versions/3.7.7/lib/python3.7/site-packages/pyarrow/fs.py", line 247, in copy_files
    chunk_size, use_threads)
  File "pyarrow/_fs.pyx", line 1258, in pyarrow._fs._copy_files_selector
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: GetFileInfo() yielded path 'bucket/nested', which is outside base dir 'bucket/nested/subdir'
```

**Comment by martindurant** [comment]
This is a different and more puzzling message!
Would you mind changing the logging line below as follows:
```diff
-         logger.debug(f"{method.upper()}: {path}, {args}, {kwargs.get('headers')}")
+         logger.debug(f"{method.upper()}: {path}, {args}, {kwargs}")
```
and trying again? That should tell us the specific prefixes that are being passed.

**Comment by krfricke** [comment]
Sure:

In 2022.8.2 (not working)
```
2022-09-27 10:35:44,270 - gcsfs.credentials - DEBUG - connect -- Connected with method google_default
2022-09-27 10:35:44,273 - gcsfs - DEBUG - _call -- GET: b/{}/o/{}, ('bucket', 'nested/subdir'), None
2022-09-27 10:35:44,274 - gcsfs.credentials - DEBUG - maybe_refresh -- GCS refresh
2022-09-27 10:35:44,587 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), None
2022-09-27 10:35:44,708 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), None

```


In 2022.7.1 (working)
```
2022-09-27 10:34:24,349 - gcsfs.credentials - DEBUG - connect -- Connected with method google_default
2022-09-27 10:34:24,356 - gcsfs - DEBUG - _call -- GET: b/{}/o/{}, ('bucket', 'nested/subdir'), {}
2022-09-27 10:34:24,357 - gcsfs.credentials - DEBUG - maybe_refresh -- GCS refresh
2022-09-27 10:34:24,782 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), {'delimiter': '/', 'prefix': 'nested/subdir/', 'maxResults': None}
2022-09-27 10:34:24,958 - gcsfs - DEBUG - _call -- GET: b/{}/o, ('bucket',), {'delimiter': None, 'prefix': 'nested/subdir/', 'maxResults': None}
```
