### ISSUE TITLE
__init__() got multiple values for keyword argument 'listings_expiry_time'

### ISSUE THREAD

**Issue by jobevers** [fsspec/gcsfs#544]
fsspec says you can use `listings_expiry_time` when creating a filesystem: https://github.com/fsspec/filesystem_spec/blob/e180aa859ef081215882b2d1b67d4bc33c040330/fsspec/spec.py#L126

But:
```
>>> fsspec.filesystem('gs', listings_expiry_time=60)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jobevers/.../lib/python3.7/site-packages/fsspec/registry.py", line 252, in filesystem
    return cls(**storage_options)
  File "/home/jobevers/.../lib/python3.7/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/home/jobevers/.../lib/python3.7/site-packages/gcsfs/core.py", line 280, in __init__
    **kwargs,
TypeError: __init__() got multiple values for keyword argument 'listings_expiry_time'
```

**Comment by martindurant** [comment]
Unfortunately, due to history and poor planning, this is called cache_timeout for gcsfs. We should probably fix that so that the upstream documented way works there too. It should be easy to add a line in gcsfs.core.GCSFileSystem, if you would care to help out @jobevers .
